export const mockData = [
  {
    name: "Dadapir Shaikh",
    email: "shaikdadapir21@gmail.com",
    country_code: "+91",
    mobile_without_country_code: "9922841004",
    company: "Software Developer",
    city: "Goa",
    state: "Ponda",
    country: "India",
    lead_owner: "test@gmail.com",
    crm_status: "DID_NOT_CONNECT",
    crm_note: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    data_source: "sarjapur_plots",
    possession_time: "Immediate",
    description: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    created_at: "2023-10-27",
  },
  {
    name: "",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "GOOD_LEAD_FOLLOW_UP",
    crm_note: "Agent Remarks: call back tomorrow\nCustomer Mood: angry",
    data_source: "leads_on_demand",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "BAD_LEAD",
    crm_note: "He Was Sad",
    data_source: "meridian_tower",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "eden_park",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "varah_swamy",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+91",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "sarjapur_plots",
    possession_time: "Immediate",
    description: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "EDEN PARK",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  }, {
    name: "Dadapir Shaikh",
    email: "shaikdadapir21@gmail.com",
    country_code: "+91",
    mobile_without_country_code: "9922841004",
    company: "Software Developer",
    city: "Goa",
    state: "Ponda",
    country: "India",
    lead_owner: "test@gmail.com",
    crm_status: "DID_NOT_CONNECT",
    crm_note: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    data_source: "sarjapur_plots",
    possession_time: "Immediate",
    description: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    created_at: "2023-10-27",
  },
  {
    name: "",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "GOOD_LEAD_FOLLOW_UP",
    crm_note: "Agent Remarks: call back tomorrow Customer Mood: angry",
    data_source: "leads_on_demand",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "BAD_LEAD",
    crm_note: "He Was Happy",
    data_source: "meridian_tower",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "eden_park",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "varah_swamy",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+91",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "sarjapur_plots",
    possession_time: "Immediate",
    description: "Agent Remarks: call back tomorrow \n Customer Mood: angry",
    created_at: "2023-10-27",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    country_code: "+1",
    mobile_without_country_code: "555-0192",
    company: "Acme Corp",
    city: "New York",
    state: "NY",
    country: "USA",
    lead_owner: "Alice Smith",
    crm_status: "SALE_DONE",
    crm_note: "He Was Happy",
    data_source: "EDEN PARK",
    possession_time: "Immediate",
    description: "Looking for 3BHK",
    created_at: "2023-10-27",
  }
];
